### ISSUE TITLE
Erro ao executar os examples

### ISSUE THREAD

**Issue by johnnyubiali** [fiorix/nitgen-bsp#3]
Ao executar os exemplos em sua pasta examples dá o seguinte rerro:

root@Ubuntu:/usr/local/lib/python2.6/dist-packages/NitgenBSP# python save_image.py 
place your finger in the reader and press enter: 
Traceback (most recent call last):
  File "save_image.py", line 16, in <module>
    finger = handler.capture()
  File "/usr/local/lib/python2.6/dist-packages/NitgenBSP/**init**.py", line 89, in capture
    self.__image_width, self.__image_height, purpose, timeout)
RuntimeError: cannot capture fingerprint

o que pode ser?

**Comment by fiorix** [comment]
Mmmm NBioAPI_Capture falhou, veja https://github.com/fiorix/nitgen-bsp/blob/master/NitgenBSP/bsp_core.c#L84

Não tenho mais nenhum device pra testar portanto não posso ajudar muito. Talvez você queira imprimir o erro pra saber mais detalhes.

Isso não é um erro do driver, e sim de operação.
