### ISSUE TITLE
How do I install it? 

### ISSUE THREAD

**Issue by kcmahip** [fiorix/nitgen-bsp#5]
python setup.py install 
running install
running build
running build_py
running build_ext
building 'NitgenBSP/_bsp_core' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/NITGEN/eNBSP/include -I/usr/include/python2.7 -c NitgenBSP/bsp_core.c -o build/temp.linux-x86_64-2.7/NitgenBSP/bsp_core.o
NitgenBSP/bsp_core.c:3:21: fatal error: NBioAPI.h: No such file or directory
 #include <NBioAPI.h>
                     ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by fiorix** [comment]
You must have the Nitgen SDK installed in order to build this.

**Comment by kcmahip** [comment]
Hey, I am using fingkey hamster for my college project. I obtained the
scanner from my teacher. If I want to use some python programs to use the
scanner as per my wish, do i need the licence for the SDK?

**Comment by fiorix** [comment]
Hey I have no idea but when I developed this I didn't need any special license.

**Comment by kcmahip** [comment]
So your project basically helps to use simple python scripts for capturing/
verifying the images scanned by the scanner? I am having a hard time
installing the SDK on my linux machine. Would you be kind enough to provide
me with any relevant links to downloads?
Thanks.
