### ISSUE TITLE
Cannot Find -lNBioBSP

### ISSUE THREAD

**Issue by prabhakaran4920** [fiorix/nitgen-bsp#7]
hi..,
while installing setup.py file I am facing this problem ""/usr/bin/ld: cannot find -lNBioBSP""
and i checked the directory /usr/bin/ld: is not available in my usr/bin.
Is nitgen-bsp support enbioscan-c1(nitgen) model-HFDUC08 ??
note: I installed the nitgen SDK in my linux
My Error :
pi@raspberrypi:~/Downloads/nitgen-bsp-master $ python setup.py install
running install
running build
running build_py
running build_ext
building 'NitgenBSP/_bsp_core' extension
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/NITGEN/eNBSP/include -I/usr/include/python2.7 -c NitgenBSP/bsp_core.c -o build/temp.linux-armv7l-2.7/NitgenBSP/bsp_core.o
arm-linux-gnueabihf-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-armv7l-2.7/NitgenBSP/bsp_core.o -lpthread -lNBioBSP -o build/lib.linux-armv7l-2.7/NitgenBSP/_bsp_core.so
/usr/bin/ld: cannot find -lNBioBSP
collect2: error: ld returned 1 exit status
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

**Comment by fiorix** [comment]
Looks like you're missing the BSP c++ libraries, or they're installed elsewhere in your system.
